argmat-clpb: argumatrix::PlTimeQry Class Reference
argumatrix::PlTimeQry Class Reference
Create a time query which can output the time information.
#include <swipl-util.hpp>
Public Member Functions
PlTimeQry (const char *name, const PlTermv &av)
Create a time query where name defines the name of the predicate and av the argument vector. The arity is deduced from av.size The predicate is located in the Prolog module user.
PlTimeQry (const char *module, const char *name, const PlTermv &av)
Same, but performs the time query lookup in the indicated module.
int next_solution ()
Generate the first (next) solution for the given query. The return value is TRUE if a solution was found, or FALSE to indicate the query could not be proven. This function may be called repeatedly until it fails to generate all solutions to the query.
Public Attributes
qid_t qid
Detailed Description
Create a time query which can output the time information.
Date
May 2016
Definition at line 180 of file swipl-util.hpp.
Constructor & Destructor Documentation
argumatrix::PlTimeQry::PlTimeQry (const char * name, const PlTermv & av) inline
Create a time query where name defines the name of the predicate and av the argument vector. The arity is deduced from av.size The predicate is located in the Prolog module user.
Method: Constructor: PlTimeQry
Parameters
const char * name
const PlTermv & av
Note
A Time Query is a query to measure the time of this query. It is equivalence to the query: time(Goal), in which the Goal is the real body of the query and is a compound term PlCompound(name, av).
Definition at line 196 of file swipl-util.hpp.
argumatrix::PlTimeQry::PlTimeQry (const char * module, const char * name, const PlTermv & av) inline
Same, but performs the time query lookup in the indicated module.
Method: Constructor: PlTimeQry
Parameters
const char * module
const char * name
const PlTermv & av
Definition at line 210 of file swipl-util.hpp.
Member Function Documentation
__inline int argumatrix::PlTimeQry::next_solution ()
Generate the first (next) solution for the given query. The return value is TRUE if a solution was found, or FALSE to indicate the query could not be proven. This function may be called repeatedly until it fails to generate all solutions to the query.
Method: next_solution FullName: public argumatrix::PlTimeQry::next_solution
Returns
int
Definition at line 261 of file swipl-util.hpp.
Referenced by argumatrix::PlReasoner::addBlTermToBvExts(), argumatrix::PlReasoner::fetchAllExts(), argumatrix::PlReasoner::findAllExts(), argumatrix::PlReasoner::printAllExts(), argumatrix::PlReasoner::printSomeExt(), argumatrix::PlReasoner::verifyExclusion(), argumatrix::PlReasoner::verifyInclusion(), and argumatrix::PlReasoner::verifyNonemptyExt().
The documentation for this class was generated from the following file:
F:/Codespace/BoostProject/argumatrix/PlReasoner/swipl-util.hpp