argmat-clpb: argumatrix::AdmissiblePlReasoner Class Reference
argumatrix::AdmissiblePlReasoner Class Reference
Public Member Functions
AdmissiblePlReasoner (const DungAF &daf, const string &sm_task="AD", streambuf *osbuff=std::cout.rdbuf())
void task_EE ()
Print all extensions (with a vector of integers {0,1,2})
void task_EX ()
void task_EC (const std::set< string > &argset)
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
void task_SC (const std::set< string > &argset)
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
void task_SE ()
Given an ${AF}=< {X}, {R}>$, enumerate some set $E {X}$ that are in ${E}_(AF)$.
void findAllExts ()
void task_DE (const std::set< string > &argset)
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a -extension of AF, i.e., S E_(AF).
void task_DN ()
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty -extension for AF.
void task_DC (const std::set< string > &argset)
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in some E E_(AF) (i.e., credulously justified).
void task_DS (const std::set< string > &argset)
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in each E E_(AF) (i.e., skeptically justified).
void consultPlFile (std::string plFile=ARG_PROLOG_FILE)
Loading the Prolog source file [argmat-clpb].
void Test_time ()
void printAllExts (const std::string &predct)
Print all extensions with respect to semantic predct.
void printAllExts (const std::string &predct, const std::set< string > &argset)
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
void printAllExts (const std::string &predct, const std::vector< int > &vecii)
void printAllExts2 (const std::string &predct)
void fetchAllExts (const std::string &predct)
void printSomeExt (const std::string &predct, const std::set< string > &argset)
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
void printSomeExt (const std::string &predct, const vector< int > &vecii)
bool verifyNonemptyExt (const std::string &predct)
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty $$-extension for AF.
bool verifyExtension (const std::string &predct, std::set< string > &argset)
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a $$-extension of AF, i.e., $S E_(AF)$.
bool verifyExtension (const std::string &predct, bitvector &bvecii)
bool isCredulouslyJustified (const std::string &predct, const std::set< string > &argset)
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in some E E_(AF) (i.e., credulously justified).
bool isSkepticallyJustified (const std::string &predct, const std::set< string > &argset)
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in each E E_(AF) (i.e., skeptically justified).
bitvector getAttacked (const bitvector &_bv)
Get the attacked arguments by arguments in _bv, \(R^+(S)\) \(R^+(S) = {x|x is attacked by S}\). \(R^+(S_bv) = D*S_bv\).
bitvector characteristic (const bitvector &_bv)
The characteristic function of an abstract argumentation framework: \(F_{AF}(S) = {A|A is acceptable wrt. S}\). F_AF(S_bv) = not{ R^+[ not(R^+(S_bv)) ] }.
bitvector characteristic ()
The characteristic function of an abstract argumentation framework with the initialization of empty set.
bitvector neutrality (const bitvector &_bv)
The neutrality function of an abstract argumentation framework: N_AF(S) = {A| All arguments that not attacked by S}. N_AF(S_bv) = not(R^+(S_bv))
bool is_conflict_free (const bitvector &_bv)
Argument set S is conflict-free? S is said to be conflict-free iff for any two arguments a,b in S such that a does not attack b.
bool is_conflict_free (const set< string > &argset)
bool is_acceptable (const bitvector &S, const bitvector &A)
Argument set A is acceptable w.r.t S? Alternately, S defends A? A can be an argument or an argument set. S defends argument (set) A iff for any argument x in X, if attacks A (or a in A) then there is an argument y in S such that y attacks x.
bool is_self_attacking (size_type idx)
Argument a is self-attacking iff it attacks itself.
bool is_admissible (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is an admissible extension. $S$ is an admissible extension iff $S F(S) N(S)$.
bool is_complete (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a complete extension. $S$ is a complete extension iff $S == F(S) N(S)$.
bool is_stable (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a stable extension. $S$ is a stable extension iff $S == N(S)$.
bool is_grounded (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a grounded extension. $S$ is a grounded extension iff it is the least fixed point of the characteristic function F.
bitvector getSelfAttackingArguments ()
Get all arguments which are self-attacking. Obviously, if an argument i attacks itself, the entry[i][i] of the attack matrix must be 1 (true). Therefore to get the set of self-attacking arguments is to get the diagonal elements of the attack matrix.
const set< bitvector > & getBvExtensions ()
Get all extensions given a specific semantics in format of bitvector. Each extension is a set of arguments which can "survive the conflict together". Here, we use a bitvector to represent an extension. Therefore, all extensions are formed an set of bit vectors, i.e., set<bitvector>. Each bitvector in set is an extension w.r.t. a given semantics. The computed extensions are stored in m_extensions, therefore, to get all extensions, it must first invoke the function computeExtension()
vector< int > getGroundedIntVector ()
Get a vector of integers {0, 1, 2}: 2 – Unknown, 1 – in grounded extension, and 0 – attacked by the grounded extension.
streambuf * setOutput (streambuf *strbuf)
Redirect the output stream to streambuf* strbuf or ostream& os. If strbuf = cout.rdbuf(), then the output is standard output. It can also redirect the output to a file by the following codes:
ofstream ofile("output.txt");
streambuf* oldsb = xxx.setOutput(ofile.rdbuf());
or
streambuf* oldsb = xxx.setOutput(ofile);
.
streambuf * setOutput (ostream &os=std::cout)
void printLabSet (const bitvector &bv_ext)
Print an extension with the form of bitvector. Assume the bitvector is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
void printLabSet (const std::set< string > &labset)
Print a set of arguments. The member m_output will determine where to print.
void printBvExts ()
Output all extensions given a specific semantics with an ostream. Each extension is a set of arguments which can "survive the conflict together". Here, we return a string to represent all extensions. For example, if there are two extensions, [a,b] and [b, d], for some problem w.r.t. a given semantics, then we return string "[[a,b],[d,c]]". If extensions is not existing, the string "[]" will return.
bitvector getGroundedExtension ()
Get the grounded extension.
void printGroundedExt ()
Print the grounded extension.
vector< int > labelSet2IntVector (const std::set< string > &label_set)
Convert a set of argument (string) labels to an integer vector of {0,1,2}, All arguments in these set, the indices is 1; otherwise 2 (representing unknown)
Protected Member Functions
void findAllExts (const std::string &predct)
Find all extensions and store them in m_extensions with the form of bitvector.
void createPlAttackMatrix ()
Create the attack matrix with the form of PlTerm, which is an input of SWI-Prolog.
void printLableExtByBlistTerm (const PlTerm &plt)
Print an extension with the form of the bool list term. Assume a bool list term is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
void printLableExtByBmatrixTerm (const PlTerm &pmtx)
Print an extension with the form of the bool matrix term. Assume a bool list term is [[0, 1, 0, 1], [0, 1, 0, 1]], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
void addBlTermToBvExts (const PlTerm &plt)
Convert a bool list term into a bitvertor, and add it to extension.
bool verifyInclusion (const std::string &predct, const vector< int > &vecii)
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a -extension that includes S.
bool verifyExclusion (const std::string &predct, const bitvector &vecB)
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a -extension that excludes S.
Protected Attributes
string m_predicate
PlTerm m_PlAtkMtx
bitmatrix m_BmAtkMtx
size_type m_argNum
const DungAF & m_daf
set< bitvector > m_extensions
vector< std::string > m_argLabels
std::ostream m_output
Detailed Description
Definition at line 37 of file AdmissiblePlReasoner.hpp.
Member Function Documentation
void argumatrix::PlReasoner::addBlTermToBvExts (const PlTerm & plt) protected inherited
Convert a bool list term into a bitvertor, and add it to extension.
Parameters
PlTerm& plt : The PlTerm is a bool list term, which represents an extension.
Returns
no return. The results are added into m_extensions.
Definition at line 303 of file PlReasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::characteristic (const bitvector & _bv) inherited
The characteristic function of an abstract argumentation framework: \(F_{AF}(S) = {A|A is acceptable wrt. S}\). F_AF(S_bv) = not{ R^+[ not(R^+(S_bv)) ] }.
Parameters
extension an extension (a set of arguments), the default is empty set.
Returns
a set of arguments in bitvector form.
Definition at line 368 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::characteristic () inherited
The characteristic function of an abstract argumentation framework with the initialization of empty set.
Returns
a set of arguments in bitvector form.
Definition at line 375 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getGroundedExtension(), and argumatrix::Reasoner::is_acceptable().
void argumatrix::PlReasoner::consultPlFile (std::string plFile = ARG_PROLOG_FILE) inherited
Loading the Prolog source file [argmat-clpb].
Method: consultPlFile
Parameters
std::string plFile
Note
SWI-Prolog supports compilation of individual or multiple Prolog source files into Quick Load Files. A Quick Load File (.qlf file) stores the contents of the file in a precompiled format. These files load considerably faster than source files and are normally more compact. They are machine-independent and may thus be loaded on any implementation of SWI-Prolog. Note, however, that clauses are stored as virtual machine instructions. Changes to the compiler will generally make old compiled files unusable. Quick Load Files are created using qcompile/1. They are loaded using consult/1 or one of the other file-loading predicates described in section 4.3. If consult/1 is given an explicit .pl file, it will load the Prolog source. When given a .qlf file, it will load the file. When no extension is specified, it will load the .qlf file when present and the .pl file otherwise.
Definition at line 253 of file PlReasoner.hpp.
void argumatrix::PlReasoner::createPlAttackMatrix () protected inherited
Create the attack matrix with the form of PlTerm, which is an input of SWI-Prolog.
Returns
no return. The result is stored in member variable m_PlAtkMtx.
Definition at line 243 of file PlReasoner.hpp.
void argumatrix::PlReasoner::fetchAllExts (const std::string & predct) inherited
Method: fetchAllExts FullName: public argumatrix::PlReasoner::fetchAllExts
Parameters
const std::string & predct
Returns
void
Return values
Definition at line 701 of file PlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::findAllExts ()
Find all extensions and store them in m_extensions with the form of bitvector.
Parameters
no argument.
Returns
no return. The results are added into m_extensions.
Definition at line 177 of file AdmissiblePlReasoner.hpp.
void argumatrix::PlReasoner::findAllExts (const std::string & predct) protected inherited
Find all extensions and store them in m_extensions with the form of bitvector.
Parameters
string& predct: The predicate.
Returns
no return. The results are added into m_extensions.
Definition at line 669 of file PlReasoner.hpp.
Referenced by findAllExts(), argumatrix::StablePlReasoner::findAllExts(), argumatrix::ConflictfreePlReasoner::findAllExts(), and argumatrix::CompletePlReasoner::findAllExts().
__inline argumatrix::bitvector argumatrix::Reasoner::getAttacked (const bitvector & _bv) inherited
Get the attacked arguments by arguments in _bv, \(R^+(S)\) \(R^+(S) = {x|x is attacked by S}\). \(R^+(S_bv) = D*S_bv\).
Parameters
_bv the bitvector with respect to the set \(S\).
Returns
a set of arguments in bitvector form.
Definition at line 360 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getGroundedIntVector(), argumatrix::Reasoner::is_conflict_free(), and argumatrix::Reasoner::neutrality().
__inline const set< bitvector > & argumatrix::Reasoner::getBvExtensions () inherited
Get all extensions given a specific semantics in format of bitvector. Each extension is a set of arguments which can "survive the conflict together". Here, we use a bitvector to represent an extension. Therefore, all extensions are formed an set of bit vectors, i.e., set<bitvector>. Each bitvector in set is an extension w.r.t. a given semantics. The computed extensions are stored in m_extensions, therefore, to get all extensions, it must first invoke the function computeExtension()
Returns
a set of bitvector, i.e., set<bitvector>.
Definition at line 400 of file Reasoner.hpp.
argumatrix::bitvector argumatrix::Reasoner::getGroundedExtension () inherited
Get the grounded extension.
Returns
a set of arguments in bitvector form.
Definition at line 484 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::is_grounded(), and argumatrix::Reasoner::printGroundedExt().
vector< int > argumatrix::Reasoner::getGroundedIntVector () inherited
Get a vector of integers {0, 1, 2}: 2 – Unknown, 1 – in grounded extension, and 0 – attacked by the grounded extension.
Returns
a vector of integers {0, 1, 2}.
Definition at line 499 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::getSelfAttackingArguments () inherited
Get all arguments which are self-attacking. Obviously, if an argument i attacks itself, the entry[i][i] of the attack matrix must be 1 (true). Therefore to get the set of self-attacking arguments is to get the diagonal elements of the attack matrix.
Returns
a set of arguments in bitvector form, if bitvector[i] = true representing the argument (with index) i is a self-attacking argument, otherwise is not.
Definition at line 414 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_acceptable (const bitvector & S, const bitvector & A) inherited
Argument set A is acceptable w.r.t S? Alternately, S defends A? A can be an argument or an argument set. S defends argument (set) A iff for any argument x in X, if attacks A (or a in A) then there is an argument y in S such that y attacks x.
Parameters
S a set of arguments.
A an argument or an argument set
Returns
true if S defends A.
Definition at line 394 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_admissible (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is an admissible extension. $S$ is an admissible extension iff $S F(S) N(S)$.
Returns
true if _bv is admissible; otherwise returns false.
Definition at line 553 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_complete (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a complete extension. $S$ is a complete extension iff $S == F(S) N(S)$.
Returns
true if _bv is complete; otherwise returns false.
Definition at line 564 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_conflict_free (const bitvector & _bv) inherited
Argument set S is conflict-free? S is said to be conflict-free iff for any two arguments a,b in S such that a does not attack b.
Parameters
extension an extension (a set of arguments).
Returns
true if S is conflict-free.
Definition at line 381 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_grounded (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a grounded extension. $S$ is a grounded extension iff it is the least fixed point of the characteristic function F.
Returns
true if _bv is grounded; otherwise returns false.
Definition at line 584 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_self_attacking (size_type idx) inherited
Argument a is self-attacking iff it attacks itself.
Parameters
idx the index of the argument w.r.t the attack matrix
Returns
true if S defends A.
Definition at line 406 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_stable (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a stable extension. $S$ is a stable extension iff $S == N(S)$.
Returns
true if _bv is stable; otherwise returns false.
Definition at line 575 of file Reasoner.hpp.
bool argumatrix::PlReasoner::isCredulouslyJustified (const std::string & predct, const std::set< string > & argset) inherited
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in some E E_(AF) (i.e., credulously justified).
Problem [DC-$$]
Definition at line 642 of file PlReasoner.hpp.
bool argumatrix::PlReasoner::isSkepticallyJustified (const std::string & predct, const std::set< string > & argset) inherited
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in each E E_(AF) (i.e., skeptically justified).
Problem [DS-$$]
Definition at line 654 of file PlReasoner.hpp.
vector< int > argumatrix::Reasoner::labelSet2IntVector (const std::set< string > & label_set) inherited
Convert a set of argument (string) labels to an integer vector of {0,1,2}, All arguments in these set, the indices is 1; otherwise 2 (representing unknown)
Returns
no return.
Definition at line 526 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::neutrality (const bitvector & _bv) inherited
The neutrality function of an abstract argumentation framework: N_AF(S) = {A| All arguments that not attacked by S}. N_AF(S_bv) = not(R^+(S_bv))
Parameters
extension an extension (a set of arguments).
Returns
a set of arguments in bitvector form.
Definition at line 547 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::characteristic(), argumatrix::Reasoner::getGroundedIntVector(), argumatrix::Reasoner::is_admissible(), argumatrix::Reasoner::is_complete(), and argumatrix::Reasoner::is_stable().
void argumatrix::PlReasoner::printAllExts (const std::string & predct) inherited
Print all extensions with respect to semantic predct.
Problem [EE-$$]
Parameters
no argument
Returns
no return.
Definition at line 430 of file PlReasoner.hpp.
Referenced by argumatrix::PlReasoner::printAllExts(), argumatrix::StablePlReasoner::task_EC(), task_EC(), argumatrix::ConflictfreePlReasoner::task_EC(), argumatrix::CompletePlReasoner::task_EC(), argumatrix::ConflictfreePlReasoner::task_EE(), task_EE(), argumatrix::StablePlReasoner::task_EE(), and argumatrix::CompletePlReasoner::task_EE().
__inline void argumatrix::PlReasoner::printAllExts (const std::string & predct, const std::set< string > & argset) inherited
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Problem [EC-$$]
Parameters
set<string>,or a Boolean vector: a set of argument
Returns
no return.
Definition at line 386 of file PlReasoner.hpp.
__inline void argumatrix::Reasoner::printBvExts () inherited
Output all extensions given a specific semantics with an ostream. Each extension is a set of arguments which can "survive the conflict together". Here, we return a string to represent all extensions. For example, if there are two extensions, [a,b] and [b, d], for some problem w.r.t. a given semantics, then we return string "[[a,b],[d,c]]". If extensions is not existing, the string "[]" will return.
Parameters
ostream& os = std::cout, output the resluts into the ostream os.
Returns
a set of bitvector, i.e., set<bitvector>.
Definition at line 428 of file Reasoner.hpp.
__inline void argumatrix::Reasoner::printGroundedExt () inherited
Print the grounded extension.
Returns
no return.
Definition at line 539 of file Reasoner.hpp.
void argumatrix::PlReasoner::printLableExtByBlistTerm (const PlTerm & plt) protected inherited
Print an extension with the form of the bool list term. Assume a bool list term is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
Parameters
PlTerm& plt : The PlTerm is a bool list term, which represents an extension.
Returns
no return.
Definition at line 271 of file PlReasoner.hpp.
void argumatrix::PlReasoner::printLableExtByBmatrixTerm (const PlTerm & pmtx) protected inherited
Print an extension with the form of the bool matrix term. Assume a bool list term is [[0, 1, 0, 1], [0, 1, 0, 1]], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
Parameters
PlTerm& plt : The PlTerm is a bool list term, which represents an extension.
Returns
no return.
Definition at line 725 of file PlReasoner.hpp.
void argumatrix::Reasoner::printLabSet (const bitvector & bv_ext) inherited
Print an extension with the form of bitvector. Assume the bitvector is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
Parameters
bitvector& bv_ext : The bv_ext is a bitvector, which represents an extension.
Returns
no return.
See also
[setOutput]
Definition at line 433 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printGroundedExt().
void argumatrix::Reasoner::printLabSet (const std::set< string > & labset) inherited
Print a set of arguments. The member m_output will determine where to print.
Parameters
const std::set<string>& labset
Returns
no return.
See also
setOutput(streambuf* strbuf = std::cout.rdbuf());
Definition at line 454 of file Reasoner.hpp.
__inline void argumatrix::PlReasoner::printSomeExt (const std::string & predct, const std::set< string > & argset) inherited
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Problem [SC-$$]
Parameters
a set of arguments.
Returns
no return.
Definition at line 468 of file PlReasoner.hpp.
Referenced by task_SC(), argumatrix::StablePlReasoner::task_SC(), argumatrix::CompletePlReasoner::task_SC(), argumatrix::StablePlReasoner::task_SE(), and argumatrix::CompletePlReasoner::task_SE().
__inline streambuf * argumatrix::Reasoner::setOutput (streambuf * strbuf) inherited
Redirect the output stream to streambuf* strbuf or ostream& os. If strbuf = cout.rdbuf(), then the output is standard output. It can also redirect the output to a file by the following codes:
ofstream ofile("output.txt");
streambuf* oldsb = xxx.setOutput(ofile.rdbuf());
or
streambuf* oldsb = xxx.setOutput(ofile);
.
Parameters
strbuf is a streambuf pointer.
Returns
return the old streambuf, which can be used to redirect the old streambuf.
Definition at line 473 of file Reasoner.hpp.
__inline streambuf * argumatrix::Reasoner::setOutput (ostream & os = std::cout) inherited
Method: setOutput FullName: public argumatrix::Reasoner::setOutput
See also
streambuf* setOutput(streambuf* strbuf = std::cout.rdbuf());
Parameters
ostream & os
Returns
streambuf*
Definition at line 479 of file Reasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_DC (const std::set< string > & argset) virtual
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in some E E_(AF) (i.e., credulously justified).
Problem [DC-$$]
Reimplemented from argumatrix::Reasoner.
Definition at line 228 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_DE (const std::set< string > & argset) virtual
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a -extension of AF, i.e., S E_(AF).
Problem [DE-$$]
Parameters
a set of arguments.
Returns
true if argset is a -extension; otherwise return false.
Reimplemented from argumatrix::Reasoner.
Definition at line 183 of file AdmissiblePlReasoner.hpp.
void argumatrix::AdmissiblePlReasoner::task_DN () virtual
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty -extension for AF.
Problem [DN-$$]
Returns
true if there exist a non-empty -extension; otherwise return false.
Reimplemented from argumatrix::Reasoner.
Definition at line 199 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_DS (const std::set< string > & argset) virtual
Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in each E E_(AF) (i.e., skeptically justified).
Problem [DS-$$]
Reimplemented from argumatrix::Reasoner.
Definition at line 243 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_EC (const std::set< string > & argset) virtual
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Problem [EC-$$]
Parameters
set<string>,or a Boolean vector: a set of argument
Returns
no return.
Reimplemented from argumatrix::Reasoner.
Definition at line 166 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_EE () virtual
Print all extensions (with a vector of integers {0,1,2})
Problem [EE-$$]
Parameters
no argument
Returns
no return.
Reimplemented from argumatrix::Reasoner.
Definition at line 160 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_SC (const std::set< string > & argset) virtual
Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Problem [SC-$$]
Parameters
a set of arguments.
Returns
no return.
Reimplemented from argumatrix::Reasoner.
Definition at line 209 of file AdmissiblePlReasoner.hpp.
__inline void argumatrix::AdmissiblePlReasoner::task_SE () virtual
Given an ${AF}=< {X}, {R}>$, enumerate some set $E {X}$ that are in ${E}_(AF)$.
Problem [SE-$$]
Parameters
a set of arguments.
Returns
no return.
Reimplemented from argumatrix::Reasoner.
Definition at line 220 of file AdmissiblePlReasoner.hpp.
bool argumatrix::PlReasoner::verifyExclusion (const std::string & predct, const bitvector & vecB) protected inherited
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a -extension that excludes S.
Parameters
a set of arguments.
Returns
true if there exist a -extension that excludes S; otherwise return false.
Definition at line 576 of file PlReasoner.hpp.
__inline bool argumatrix::PlReasoner::verifyExtension (const std::string & predct, std::set< string > & argset) inherited
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a $$-extension of AF, i.e., $S E_(AF)$.
Problem [DE-$$]
Parameters
a set of arguments.
Returns
true if argset is a -extension; otherwise return false.
Definition at line 609 of file PlReasoner.hpp.
bool argumatrix::PlReasoner::verifyInclusion (const std::string & predct, const vector< int > & vecii) protected inherited
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a -extension that includes S.
Parameters
a set of arguments.
Returns
true if there exist a -extension that includes S; otherwise return false.
Definition at line 543 of file PlReasoner.hpp.
bool argumatrix::PlReasoner::verifyNonemptyExt (const std::string & predct) inherited
Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty $$-extension for AF.
Problem [DN-$$]
Returns
true if there exist a non-empty -extension; otherwise return false.
Definition at line 510 of file PlReasoner.hpp.
Member Data Documentation
vector< std::string > argumatrix::Reasoner::m_argLabels protected inherited
Dung's abstract argumentation framework
Definition at line 346 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printLabSet().
size_type argumatrix::Reasoner::m_argNum protected inherited
The number of arguments
Definition at line 339 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::characteristic(), argumatrix::Reasoner::getGroundedExtension(), argumatrix::Reasoner::getGroundedIntVector(), and argumatrix::Reasoner::labelSet2IntVector().
bitmatrix argumatrix::Reasoner::m_BmAtkMtx protected inherited
The bitmatrix of the Dung Abstract argumentation framework. We can access all attackers of an argument. The attackers of the argument with index i is m_BmAtkMtx[i].
Definition at line 334 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getAttacked(), argumatrix::Reasoner::getSelfAttackingArguments(), and argumatrix::Reasoner::is_self_attacking().
const DungAF& argumatrix::Reasoner::m_daf protected inherited
Dung's abstract argumentation framework
Definition at line 342 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::is_conflict_free(), argumatrix::Reasoner::labelSet2IntVector(), and argumatrix::Reasoner::printBvExts().
std::ostream argumatrix::Reasoner::m_output protected inherited
Where to output
Definition at line 348 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printBvExts(), argumatrix::Reasoner::printGroundedExt(), argumatrix::Reasoner::printLabSet(), and argumatrix::Reasoner::setOutput().
The documentation for this class was generated from the following file:
F:/Codespace/BoostProject/argumatrix/PlReasoner/AdmissiblePlReasoner.hpp