argmat-clpb: argumatrix::PreferredReasoner Class Reference
argumatrix::PreferredReasoner Class Reference
#include <PreferredReasoner.hpp>
Public Member Functions
PreferredReasoner (const DungAF &daf, streambuf *osbuff=std::cout.rdbuf())
void computeExtensions ()
bitvector getAttackers (const bitvector &_bv)
bitvector getAttacked (const bitvector &_bv)
Get the attacked arguments by arguments in _bv, \(R^+(S)\) \(R^+(S) = {x|x is attacked by S}\). \(R^+(S_bv) = D*S_bv\).
bitvector characteristic (const bitvector &_bv)
The characteristic function of an abstract argumentation framework: \(F_{AF}(S) = {A|A is acceptable wrt. S}\). F_AF(S_bv) = not{ R^+[ not(R^+(S_bv)) ] }.
bitvector characteristic ()
The characteristic function of an abstract argumentation framework with the initialization of empty set.
bitvector neutrality (const bitvector &_bv)
The neutrality function of an abstract argumentation framework: N_AF(S) = {A| All arguments that not attacked by S}. N_AF(S_bv) = not(R^+(S_bv))
bool is_conflict_free (const bitvector &_bv)
Argument set S is conflict-free? S is said to be conflict-free iff for any two arguments a,b in S such that a does not attack b.
bool is_conflict_free (const set< string > &argset)
bool is_acceptable (const bitvector &S, const bitvector &A)
Argument set A is acceptable w.r.t S? Alternately, S defends A? A can be an argument or an argument set. S defends argument (set) A iff for any argument x in X, if attacks A (or a in A) then there is an argument y in S such that y attacks x.
bool is_self_attacking (size_type idx)
Argument a is self-attacking iff it attacks itself.
bool is_admissible (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is an admissible extension. $S$ is an admissible extension iff $S F(S) N(S)$.
bool is_complete (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a complete extension. $S$ is a complete extension iff $S == F(S) N(S)$.
bool is_stable (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a stable extension. $S$ is a stable extension iff $S == N(S)$.
bool is_grounded (const bitvector &_bv)
To decide whether a set of arguments (with the form of bitvector) is a grounded extension. $S$ is a grounded extension iff it is the least fixed point of the characteristic function F.
bitvector getSelfAttackingArguments ()
Get all arguments which are self-attacking. Obviously, if an argument i attacks itself, the entry[i][i] of the attack matrix must be 1 (true). Therefore to get the set of self-attacking arguments is to get the diagonal elements of the attack matrix.
const set< bitvector > & getBvExtensions ()
Get all extensions given a specific semantics in format of bitvector. Each extension is a set of arguments which can "survive the conflict together". Here, we use a bitvector to represent an extension. Therefore, all extensions are formed an set of bit vectors, i.e., set<bitvector>. Each bitvector in set is an extension w.r.t. a given semantics. The computed extensions are stored in m_extensions, therefore, to get all extensions, it must first invoke the function computeExtension()
vector< int > getGroundedIntVector ()
Get a vector of integers {0, 1, 2}: 2 – Unknown, 1 – in grounded extension, and 0 – attacked by the grounded extension.
streambuf * setOutput (streambuf *strbuf)
Redirect the output stream to streambuf* strbuf or ostream& os. If strbuf = cout.rdbuf(), then the output is standard output. It can also redirect the output to a file by the following codes:
ofstream ofile("output.txt");
streambuf* oldsb = xxx.setOutput(ofile.rdbuf());
or
streambuf* oldsb = xxx.setOutput(ofile);
.
streambuf * setOutput (ostream &os=std::cout)
void printLabSet (const bitvector &bv_ext)
Print an extension with the form of bitvector. Assume the bitvector is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
void printLabSet (const std::set< string > &labset)
Print a set of arguments. The member m_output will determine where to print.
void printBvExts ()
Output all extensions given a specific semantics with an ostream. Each extension is a set of arguments which can "survive the conflict together". Here, we return a string to represent all extensions. For example, if there are two extensions, [a,b] and [b, d], for some problem w.r.t. a given semantics, then we return string "[[a,b],[d,c]]". If extensions is not existing, the string "[]" will return.
bitvector getGroundedExtension ()
Get the grounded extension.
void printGroundedExt ()
Print the grounded extension.
vector< int > labelSet2IntVector (const std::set< string > &label_set)
Convert a set of argument (string) labels to an integer vector of {0,1,2}, All arguments in these set, the indices is 1; otherwise 2 (representing unknown)
virtual void task_EE ()
Problem [EE-$$] Print all extensions.
virtual void task_EX ()
virtual void task_EC (const std::set< string > &argset)
Problem [EC-$$] Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
virtual void task_SC (const std::set< string > &argset)
Problem [SC-$$] Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
virtual void task_SE ()
Problem [SE-$$] Given an ${AF}=< {X}, {R}>$, enumerate some set $E {X}$ that are in ${E}_(AF)$.
virtual void task_DE (const std::set< string > &argset)
Problem [DE-$$] Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a -extension of AF, i.e., S E_(AF).
virtual void task_DN ()
Problem [DN-$$] Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty -extension for AF.
virtual void task_DC (const std::set< string > &argset)
Problem [DC-$$] Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in some E E_(AF) (i.e., credulously justified).
virtual void task_DS (const std::set< string > &argset)
Problem [DS-$$] Given an $AF = <X,R>$ and an argument s X (respectively, a set of arguments $S X$). Decide whether s contained (respectively, S included) in each E E_(AF) (i.e., skeptically justified).
Protected Attributes
bitmatrix m_BmAtkMtx
size_type m_argNum
const DungAF & m_daf
set< bitvector > m_extensions
vector< std::string > m_argLabels
std::ostream m_output
Detailed Description
This reasoner for Dung theories performs inference on the preferred extension. Computes the (unique) grounded extension, i.e., the least fixpoint of the characteristic function.
Definition at line 38 of file PreferredReasoner.hpp.
Member Function Documentation
__inline argumatrix::bitvector argumatrix::Reasoner::characteristic (const bitvector & _bv) inherited
The characteristic function of an abstract argumentation framework: \(F_{AF}(S) = {A|A is acceptable wrt. S}\). F_AF(S_bv) = not{ R^+[ not(R^+(S_bv)) ] }.
Parameters
extension an extension (a set of arguments), the default is empty set.
Returns
a set of arguments in bitvector form.
Definition at line 368 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::characteristic () inherited
The characteristic function of an abstract argumentation framework with the initialization of empty set.
Returns
a set of arguments in bitvector form.
Definition at line 375 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getGroundedExtension(), and argumatrix::Reasoner::is_acceptable().
void argumatrix::PreferredReasoner::computeExtensions ()
Compute all extensions given a specific semantics. Each extension is a set of arguments. Here, we use a bitvector to represent an extension. The results are stored in m_extensions. When a new extension bv is computed, it can be added to m_extensions by m_extensions.push_back(bv).
Returns
no return. The results are stored in m_extensions.
Definition at line 97 of file PreferredReasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::getAttacked (const bitvector & _bv) inherited
Get the attacked arguments by arguments in _bv, \(R^+(S)\) \(R^+(S) = {x|x is attacked by S}\). \(R^+(S_bv) = D*S_bv\).
Parameters
_bv the bitvector with respect to the set \(S\).
Returns
a set of arguments in bitvector form.
Definition at line 360 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getGroundedIntVector(), argumatrix::Reasoner::is_conflict_free(), and argumatrix::Reasoner::neutrality().
bitvector argumatrix::PreferredReasoner::getAttackers (const bitvector & _bv)
Get attackers of arguments in _bv, R^-(S) R^-(S) = {x|x attacks some argument in S}. R^-(S_bv) = D^T*S_bv
Parameters
_bv the bitvector of a set of arguments S.
Returns
a set of arguments in bitvector form.
Definition at line 246 of file PreferredReasoner.hpp.
__inline const set< bitvector > & argumatrix::Reasoner::getBvExtensions () inherited
Get all extensions given a specific semantics in format of bitvector. Each extension is a set of arguments which can "survive the conflict together". Here, we use a bitvector to represent an extension. Therefore, all extensions are formed an set of bit vectors, i.e., set<bitvector>. Each bitvector in set is an extension w.r.t. a given semantics. The computed extensions are stored in m_extensions, therefore, to get all extensions, it must first invoke the function computeExtension()
Returns
a set of bitvector, i.e., set<bitvector>.
Definition at line 400 of file Reasoner.hpp.
argumatrix::bitvector argumatrix::Reasoner::getGroundedExtension () inherited
Get the grounded extension.
Returns
a set of arguments in bitvector form.
Definition at line 484 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::is_grounded(), and argumatrix::Reasoner::printGroundedExt().
vector< int > argumatrix::Reasoner::getGroundedIntVector () inherited
Get a vector of integers {0, 1, 2}: 2 – Unknown, 1 – in grounded extension, and 0 – attacked by the grounded extension.
Returns
a vector of integers {0, 1, 2}.
Definition at line 499 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::getSelfAttackingArguments () inherited
Get all arguments which are self-attacking. Obviously, if an argument i attacks itself, the entry[i][i] of the attack matrix must be 1 (true). Therefore to get the set of self-attacking arguments is to get the diagonal elements of the attack matrix.
Returns
a set of arguments in bitvector form, if bitvector[i] = true representing the argument (with index) i is a self-attacking argument, otherwise is not.
Definition at line 414 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_acceptable (const bitvector & S, const bitvector & A) inherited
Argument set A is acceptable w.r.t S? Alternately, S defends A? A can be an argument or an argument set. S defends argument (set) A iff for any argument x in X, if attacks A (or a in A) then there is an argument y in S such that y attacks x.
Parameters
S a set of arguments.
A an argument or an argument set
Returns
true if S defends A.
Definition at line 394 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_admissible (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is an admissible extension. $S$ is an admissible extension iff $S F(S) N(S)$.
Returns
true if _bv is admissible; otherwise returns false.
Definition at line 553 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_complete (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a complete extension. $S$ is a complete extension iff $S == F(S) N(S)$.
Returns
true if _bv is complete; otherwise returns false.
Definition at line 564 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_conflict_free (const bitvector & _bv) inherited
Argument set S is conflict-free? S is said to be conflict-free iff for any two arguments a,b in S such that a does not attack b.
Parameters
extension an extension (a set of arguments).
Returns
true if S is conflict-free.
Definition at line 381 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_grounded (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a grounded extension. $S$ is a grounded extension iff it is the least fixed point of the characteristic function F.
Returns
true if _bv is grounded; otherwise returns false.
Definition at line 584 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_self_attacking (size_type idx) inherited
Argument a is self-attacking iff it attacks itself.
Parameters
idx the index of the argument w.r.t the attack matrix
Returns
true if S defends A.
Definition at line 406 of file Reasoner.hpp.
__inline bool argumatrix::Reasoner::is_stable (const bitvector & _bv) inherited
To decide whether a set of arguments (with the form of bitvector) is a stable extension. $S$ is a stable extension iff $S == N(S)$.
Returns
true if _bv is stable; otherwise returns false.
Definition at line 575 of file Reasoner.hpp.
vector< int > argumatrix::Reasoner::labelSet2IntVector (const std::set< string > & label_set) inherited
Convert a set of argument (string) labels to an integer vector of {0,1,2}, All arguments in these set, the indices is 1; otherwise 2 (representing unknown)
Returns
no return.
Definition at line 526 of file Reasoner.hpp.
__inline argumatrix::bitvector argumatrix::Reasoner::neutrality (const bitvector & _bv) inherited
The neutrality function of an abstract argumentation framework: N_AF(S) = {A| All arguments that not attacked by S}. N_AF(S_bv) = not(R^+(S_bv))
Parameters
extension an extension (a set of arguments).
Returns
a set of arguments in bitvector form.
Definition at line 547 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::characteristic(), argumatrix::Reasoner::getGroundedIntVector(), argumatrix::Reasoner::is_admissible(), argumatrix::Reasoner::is_complete(), and argumatrix::Reasoner::is_stable().
__inline void argumatrix::Reasoner::printBvExts () inherited
Output all extensions given a specific semantics with an ostream. Each extension is a set of arguments which can "survive the conflict together". Here, we return a string to represent all extensions. For example, if there are two extensions, [a,b] and [b, d], for some problem w.r.t. a given semantics, then we return string "[[a,b],[d,c]]". If extensions is not existing, the string "[]" will return.
Parameters
ostream& os = std::cout, output the resluts into the ostream os.
Returns
a set of bitvector, i.e., set<bitvector>.
Definition at line 428 of file Reasoner.hpp.
__inline void argumatrix::Reasoner::printGroundedExt () inherited
Print the grounded extension.
Returns
no return.
Definition at line 539 of file Reasoner.hpp.
void argumatrix::Reasoner::printLabSet (const bitvector & bv_ext) inherited
Print an extension with the form of bitvector. Assume the bitvector is [0, 1, 0, 1], the arguments corresponding to entry 1 will be print. The member m_output will determine where to print.
Parameters
bitvector& bv_ext : The bv_ext is a bitvector, which represents an extension.
Returns
no return.
See also
[setOutput]
Definition at line 433 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printGroundedExt().
void argumatrix::Reasoner::printLabSet (const std::set< string > & labset) inherited
Print a set of arguments. The member m_output will determine where to print.
Parameters
const std::set<string>& labset
Returns
no return.
See also
setOutput(streambuf* strbuf = std::cout.rdbuf());
Definition at line 454 of file Reasoner.hpp.
__inline streambuf * argumatrix::Reasoner::setOutput (streambuf * strbuf) inherited
Redirect the output stream to streambuf* strbuf or ostream& os. If strbuf = cout.rdbuf(), then the output is standard output. It can also redirect the output to a file by the following codes:
ofstream ofile("output.txt");
streambuf* oldsb = xxx.setOutput(ofile.rdbuf());
or
streambuf* oldsb = xxx.setOutput(ofile);
.
Parameters
strbuf is a streambuf pointer.
Returns
return the old streambuf, which can be used to redirect the old streambuf.
Definition at line 473 of file Reasoner.hpp.
__inline streambuf * argumatrix::Reasoner::setOutput (ostream & os = std::cout) inherited
Method: setOutput FullName: public argumatrix::Reasoner::setOutput
See also
streambuf* setOutput(streambuf* strbuf = std::cout.rdbuf());
Parameters
ostream & os
Returns
streambuf*
Definition at line 479 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_DE (const std::set< string > & argset) inline virtual inherited
Problem [DE-$$] Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether S is a -extension of AF, i.e., S E_(AF).
Parameters
a set of arguments.
Returns
true if argset is a -extension; otherwise return false.
Note
For this task, the set<string>& argset can be empty, which means to decide whether the empty set is a $$-extension of AF. This indicates that the option -a is not necessary, then the default set<string>& argset is empty.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 303 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_DN () inline virtual inherited
Problem [DN-$$] Given an $AF = <X,R>$ and a set of arguments $S X$. Decide whether there exist a non-empty -extension for AF.
Returns
true if there exist a non-empty -extension; otherwise return false.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 313 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_EC (const std::set< string > & argset) inline virtual inherited
Problem [EC-$$] Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate all sets $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Parameters
set<string>,or a Boolean vector: a set of argument
Returns
no return.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 267 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_EE () inline virtual inherited
Problem [EE-$$] Print all extensions.
Parameters
no argument
Returns
no return.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 254 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_SC (const std::set< string > & argset) inline virtual inherited
Problem [SC-$$] Given an ${AF}=< {X}, {R}>$ and an argument $s {X}$ (respectively, a set of arguments $S {X}$), enumerate some set $E {X}$ such that $E {E}_(AF)$ and $s E$ (respectively, $S E$).
Parameters
a set of arguments.
Returns
no return.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 280 of file Reasoner.hpp.
virtual void argumatrix::Reasoner::task_SE () inline virtual inherited
Problem [SE-$$] Given an ${AF}=< {X}, {R}>$, enumerate some set $E {X}$ that are in ${E}_(AF)$.
Parameters
a set of arguments.
Returns
no return.
Reimplemented in argumatrix::CompletePlReasoner, argumatrix::AdmissiblePlReasoner, argumatrix::ConflictfreePlReasoner, argumatrix::StablePlReasoner, and argumatrix::GroundedReasoner.
Definition at line 290 of file Reasoner.hpp.
Member Data Documentation
vector< std::string > argumatrix::Reasoner::m_argLabels protected inherited
Dung's abstract argumentation framework
Definition at line 346 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printLabSet().
size_type argumatrix::Reasoner::m_argNum protected inherited
The number of arguments
Definition at line 339 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::characteristic(), argumatrix::Reasoner::getGroundedExtension(), argumatrix::Reasoner::getGroundedIntVector(), and argumatrix::Reasoner::labelSet2IntVector().
bitmatrix argumatrix::Reasoner::m_BmAtkMtx protected inherited
The bitmatrix of the Dung Abstract argumentation framework. We can access all attackers of an argument. The attackers of the argument with index i is m_BmAtkMtx[i].
Definition at line 334 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::getAttacked(), argumatrix::Reasoner::getSelfAttackingArguments(), and argumatrix::Reasoner::is_self_attacking().
const DungAF& argumatrix::Reasoner::m_daf protected inherited
Dung's abstract argumentation framework
Definition at line 342 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::is_conflict_free(), argumatrix::Reasoner::labelSet2IntVector(), and argumatrix::Reasoner::printBvExts().
std::ostream argumatrix::Reasoner::m_output protected inherited
Where to output
Definition at line 348 of file Reasoner.hpp.
Referenced by argumatrix::Reasoner::printBvExts(), argumatrix::Reasoner::printGroundedExt(), argumatrix::Reasoner::printLabSet(), and argumatrix::Reasoner::setOutput().
The documentation for this class was generated from the following file:
F:/Codespace/BoostProject/argumatrix/dung_theory/PreferredReasoner.hpp