argmat-clpb: argumatrix::bitvector Class Reference
argumatrix::bitvector Class Reference
Public Member Functions
bitvector (size_type _sz, unsigned long value=0)
bitvector (const std::string &_s)
bitvector (const dynamic_bitset< block_type > &_db)
bool operator* (const bitvector &_bv)
bool is_emptyset ()
To decide whether the bitvector of an argument set is empty-set? If all entries of this bitvector are 0's, then it is an empty set, and this function return true, else return false. we must discriminate this function from the function empty(), which is used to determine the size of the bitvector is zero. This function is the same as the function none().
bool is_universal ()
To decide whether the bitvector of an argument set is universal? If all entries of this bitvector are 1's, then it is an universal set, and this function return true, else return false.
bool Increase ()
Static Public Member Functions
static bitvector EmptySet (size_type _sz)
Create an empty set (all 0's) or a universal set (all 1's) under a given size.
static bitvector UniversalSet (size_type _sz)
Detailed Description
Definition at line 60 of file bitvector.hpp.
Member Function Documentation
__inline argumatrix::bitvector argumatrix::bitvector::EmptySet (size_type _sz) static
Create an empty set (all 0's) or a universal set (all 1's) under a given size.
Parameters
_sz the size of the empty set or the universal set
Returns
the bitvector of the empty set or the universal set.
Definition at line 126 of file bitvector.hpp.
Referenced by argumatrix::Reasoner::characteristic(), argumatrix::PreferredReasoner::computeExtensions(), argumatrix::Reasoner::getGroundedExtension(), and argumatrix::Reasoner::getGroundedIntVector().
bool argumatrix::bitvector::Increase ()
increaser the bit vector with 1.
Parameters
_sz the size of the empty set or the universal set
Returns
the bitvector of the empty set or the universal set.
Definition at line 141 of file bitvector.hpp.
bool argumatrix::bitvector::is_emptyset () inline
To decide whether the bitvector of an argument set is empty-set? If all entries of this bitvector are 0's, then it is an empty set, and this function return true, else return false. we must discriminate this function from the function empty(), which is used to determine the size of the bitvector is zero. This function is the same as the function none().
Returns
true if all entries of the bitvector are 0's, otherwise return false.
Definition at line 120 of file bitvector.hpp.
Referenced by argumatrix::PreferredReasoner::computeExtensions(), and argumatrix::GroundedReasoner::task_DN().
__inline bool argumatrix::bitvector::operator* (const bitvector & _bv)
The multiplication of two bitvector. Assume A=[a_1, a_2, ..., a_n] and B=[b_1, b_2, ..., b_n], the multiplication of A*B = (a_1*b_1)+(a_2*b_2)+...+(a_n*b_n). This operation is equivalent in function to determine whether A intersects with B.
Parameters
two bitvector a and b
Returns
the bool value of A*B.
Definition at line 114 of file bitvector.hpp.
The documentation for this class was generated from the following file:
F:/Codespace/BoostProject/argumatrix/bitmatrix/bitvector.hpp